# .github/workflows/docker-build-push.yml
name: Build, Push to DockerHub and Update K8s Manifest

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 3: Build and push Docker image
      - name: Build and push Vote-app Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./vote
          file: ./vote/Dockerfile
          push: true
          tags: stacko/vote-app:${{ github.run_number }}
      
      # Step 4: Update Kubernetes manifest with new image tag
      - name: Update Kubernetes manifest with new image tag
        run: |
          chmod +x ./update-deployment.sh
          ./update-deployment.sh ${{ github.run_number }}